name: Server Health Check

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  health-check:
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v4
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests deta

      - name: Run health check script
        run: python health_check.py
        env:
          DETA_PROJECT_KEY: ${{ secrets.DETA_PROJECT_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      
